log:
  show: True
  level: 10
program:
  start: "9:15"
  stop: "15:15"
trade:
  start: "9:30"
  stop: "15:00"
  base: NIFTY
NIFTY:
  base: NIFTY
  option_exchange: NFO
  expiry: 16-SEP-2025
  quantity: 75
  depth: 5
  profit: 1
  premium: 100
