log:
  show: True
  level: 10
program:
  start: "9:15"
  stop: "15:15"
base: NIFTY
ma:
  - type: ema
    period: 3
    price: low
  - type: sma
    period: 9
    price: close
NIFTY:
  symbol: NIFTY
  option_exchange: NFO
  lots: 1
  profit: 1
  premium: 100
BANKNIFTY:
  symbol: BANKNIFTY
  option_exchange: NFO
  lots: 1
  profit: 1
  premium: 100